version: "3.8"

services:
  postgree:
    image: postgres
    container_name: gestao_vagas_postgree
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=gestao_vagas
